pipeline {
  agent {
    label 'openstack'
  }
  environment {
    BRANCH = 'master'
    ARCH = 'x86_64'
    DISTRO = 'ubuntu'
    RELEASE = 'focal'

  }
  stages {
    stage('Clone Repos') {
      steps{
        dir('sources') {
            git branch: "${BRANCH}",
                url: 'https://github.com/fortnebula/bullpup.git'
          }
      }
    }
    stage('Prep Builder') {
      steps{
        sh 'sudo apt-get update && sudo apt-get install -y golang-go debootstrap rsync gpg squashfs-tools git build-essential'
        sh 'go get -d -v github.com/lxc/distrobuilder/distrobuilder'
        sh 'cd $HOME/go/src/github.com/lxc/distrobuilder && make'
      }
    }
    stage('Build Keystone') {
      steps{
        sh "sudo $HOME/go/bin/distrobuilder build-lxc containers/images/keystone.yaml -o image.release=${RELEASE}"
        sh 'mv rootfs.tar.xz keystone.tar.xz'
        sh 'mv meta.tar.xz keystone-meta.tar.xz'

      }
    }
  }
  post {
      always {
          archiveArtifacts artifacts: "*.xz", fingerprint: true
      }
  }
}
